# Generated by Django 3.0.1 on 2020-04-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('Card_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Card_Number', models.CharField(max_length=20, unique=True)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Expiry_Date', models.DateField()),
                ('Security_Number', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Card',
                'db_table': 'DebitCard',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('Institute_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30, unique=True)),
                ('Address', models.CharField(max_length=60)),
                ('URL', models.CharField(max_length=40, unique=True)),
                ('Token', models.IntegerField(default=0)),
                ('Card_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_Module.DebitCard', verbose_name='Card')),
            ],
            options={
                'db_table': 'Institute',
            },
        ),
        migrations.CreateModel(
            name='InstituteOwner',
            fields=[
                ('InstituteOwner_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CNIC', models.CharField(max_length=15, unique=True)),
                ('DOB', models.DateField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Contact_Number', models.CharField(max_length=11, unique=True)),
                ('Password', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=30, unique=True)),
                ('Institute_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_Module.Institute')),
            ],
            options={
                'db_table': 'InstituteOwner',
            },
        ),
        migrations.AddConstraint(
            model_name='debitcard',
            constraint=models.UniqueConstraint(fields=('Card_Number',), name='unique_Card_Number'),
        ),
        migrations.AddConstraint(
            model_name='instituteowner',
            constraint=models.UniqueConstraint(fields=('CNIC',), name='unique_CNIC'),
        ),
        migrations.AddConstraint(
            model_name='instituteowner',
            constraint=models.UniqueConstraint(fields=('Contact_Number',), name='unique_Contact_Number'),
        ),
        migrations.AddConstraint(
            model_name='instituteowner',
            constraint=models.UniqueConstraint(fields=('Email',), name='unique_Email'),
        ),
        migrations.AddConstraint(
            model_name='institute',
            constraint=models.UniqueConstraint(fields=('Name',), name='unique_Name'),
        ),
        migrations.AddConstraint(
            model_name='institute',
            constraint=models.UniqueConstraint(fields=('URL',), name='unique_URL'),
        ),
    ]
